version: '3.8'

services:
  db:
    image: postgres:15
    container_name: wedding-db
    environment:
      POSTGRES_DB: wedding
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - wedding-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: wedding-backend
    ports:
      - "8989:8989"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wedding
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  wedding-data:
